name: Cypress test CI
on: 
  push:
    branches: [ sveltekit_tailwindcss_frontend ]
jobs:
  E2E-test:
    runs-on: ubuntu-20.04
    steps:
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - name: Check out repository code
        uses: actions/checkout@v2
      
      
